generator_class: lifetime_feature_generator.LifetimeFeatureGenerator
data_bundles_dir: data_bundles

# The additional arguments that will be given when initiating the data generator
# object.
generator_kwargs:
  h5py_hdf_path:
    h5py.h5
  data_csv_path:
    lifetime.csv
